name: "Docker Build, Push, and Scan"
description: "Builds a Docker image, optionally pushes to Docker Hub, and runs Trivy vulnerability scan."

inputs:
  image-base-name:
    description: "Base name for the Docker image (e.g., a13labs/comfyui-frontend)"
    required: true
  dockerfile-path:
    description: "Path to the Dockerfile (e.g., Dockerfile.frontend)"
    required: true
  push-image:
    description: "Whether to push the image to Docker Hub"
    required: true
  run-trivy-scan:
    description: "Whether to run Trivy vulnerability scanner"
    required: true
  dockerhub-username:
    description: "Docker Hub username for login"
    required: true
  dockerhub-token:
    description: "Docker Hub token for login"
    required: true

outputs:
  tags:
    description: "The tags generated for the image by docker/metadata-action"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "The labels generated for the image by docker/metadata-action"
    value: ${{ steps.meta.outputs.labels }}
  version:
    description: "The primary version tag generated by docker/metadata-action (used for Trivy scan)"
    value: ${{ steps.meta.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-base-name }}
        tags: |
          type=schedule
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ inputs.dockerhub-username != '' && inputs.dockerhub-token != '' }} # Only login if credentials provided
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and Push
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push-image }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.dockerfile-path }}

    - name: Run Trivy vulnerability scanner
      if: ${{ inputs.run-trivy-scan == true }}
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: "${{ inputs.image-base-name }}:${{ steps.meta.outputs.version }}"
        format: "table"
        exit-code: "1"
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "CRITICAL,HIGH"
