name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on tags that start with 'v'
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Build, Push, and Scan
        uses: ./.github/actions/docker-build-push-trivy
        with:
          image-base-name: 'a13labs/comfyui'
          dockerfile-path: 'Dockerfile.comfyui'
          push-image: true 
          run-trivy-scan: true
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Build, Push, and Scan
        uses: ./.github/actions/docker-build-push-trivy
        with:
          image-base-name: 'a13labs/trellis'
          dockerfile-path: 'Dockerfile.trellis'
          push-image: true # For backend, we build, push and scan
          run-trivy-scan: false # Assuming no scan for backend, adjust if needed
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
