name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on tags that start with 'v'
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build, Push, and Scan
        uses: ./.github/actions/docker-build-push-trivy
        with:
          image-base-name: 'a13labs/comfyui-frontend'
          dockerfile-path: 'Dockerfile.frontend'
          push-image: true # For frontend, we only build and scan
          run-trivy-scan: true
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build, Push, and Scan
        uses: ./.github/actions/docker-build-push-trivy
        with:
          image-base-name: 'a13labs/comfyui-backend'
          dockerfile-path: 'Dockerfile.backend'
          push-image: true # For backend, we build, push and scan
          run-trivy-scan: false # Assuming no scan for backend, adjust if needed
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
